services:

  nginx:
    image: nginx
   
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/data:/var/www/html
      - ./nginx/data/swagger-docs:/var/www/html/swagger-docs
    
    ports: 
      - 8080:8080

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    volumes:
       - ./mssql:/usr/sbin/mssql
    environment:  
        ACCEPT_EULA: Y         
        MSSQL_SA_PASSWORD: 2a1sp-msX01
    ports:
       - 1433:1433

  db:
    image: mysql:8.4
    restart: always
    volumes:
      - ./mysql:/usr/sbin/mysql
    environment:          
        MYSQL_ROOT_PASSWORD: 2a1sp-myX01
        MYSQL_DATABASE: AuthUserDB
    ports:
      - 3306:3306

 
    

  
    

  
    
 

  
         
 
           
          

       
